%% 1-1 grid percentage
for i=1:length(actTime2)
    minn=find(comparement(:,2)==i,1);
    maxx=find(comparement(:,2)==i,1,'last');
    percentage(i,1)=length(find(comparement(minn:maxx,1)==i))/length(find(comparement(:,2)==i))*100;
end

%% 1st neighbor percentage
for i=1:length(actTime2)
    minn=find(comparement(:,2)==i,1);
    maxx=find(comparement(:,2)==i,1,'last');
    switch i
        case 1
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==2))+length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==8)))...
                /length(find(comparement(:,2)==i))*100;
        case 2
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==1))+length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==8))...
                +length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==7)))...
                /length(find(comparement(:,2)==i))*100;
        case 3
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==2))+length(find(comparement(minn:maxx,1)==4))+length(find(comparement(minn:maxx,1)==6))...
                +length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==5)))...
                /length(find(comparement(:,2)==i))*100;
        case 4
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==5)))...
                /length(find(comparement(:,2)==i))*100;
        case 5
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==4))+length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==6))...
                +length(find(comparement(minn:maxx,1)==11))+length(find(comparement(minn:maxx,1)==12)))...
                /length(find(comparement(:,2)==i))*100;
        case 6
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==2))+length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==4))...
                +length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==5))+length(find(comparement(minn:maxx,1)==10))...
                +length(find(comparement(minn:maxx,1)==11))++length(find(comparement(minn:maxx,1)==12)))...
                /length(find(comparement(:,2)==i))*100;
        case 7
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==1))+length(find(comparement(minn:maxx,1)==2))+length(find(comparement(minn:maxx,1)==3))...
                +length(find(comparement(minn:maxx,1)==8))+length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==9))...
                +length(find(comparement(minn:maxx,1)==10))++length(find(comparement(minn:maxx,1)==11)))...
                /length(find(comparement(:,2)==i))*100;
        case 8
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==9))+length(find(comparement(minn:maxx,1)==10))+length(find(comparement(minn:maxx,1)==7))...
                +length(find(comparement(minn:maxx,1)==1))+length(find(comparement(minn:maxx,1)==2)))...
                /length(find(comparement(:,2)==i))*100;
        case 9
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==16))+length(find(comparement(minn:maxx,1)==15))+length(find(comparement(minn:maxx,1)==10))...
                +length(find(comparement(minn:maxx,1)==8))+length(find(comparement(minn:maxx,1)==7)))...
                /length(find(comparement(:,2)==i))*100;
        case 10
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==16))+length(find(comparement(minn:maxx,1)==15))+length(find(comparement(minn:maxx,1)==14))...
                +length(find(comparement(minn:maxx,1)==9))+length(find(comparement(minn:maxx,1)==11))+length(find(comparement(minn:maxx,1)==8))...
                +length(find(comparement(minn:maxx,1)==7))++length(find(comparement(minn:maxx,1)==6)))...
                /length(find(comparement(:,2)==i))*100;
        case 11
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==15))+length(find(comparement(minn:maxx,1)==14))+length(find(comparement(minn:maxx,1)==13))...
                +length(find(comparement(minn:maxx,1)==10))+length(find(comparement(minn:maxx,1)==12))+length(find(comparement(minn:maxx,1)==7))...
                +length(find(comparement(minn:maxx,1)==6))++length(find(comparement(minn:maxx,1)==5)))...
                /length(find(comparement(:,2)==i))*100;
        case 12
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==5))+length(find(comparement(minn:maxx,1)==11))...
                +length(find(comparement(minn:maxx,1)==14))+length(find(comparement(minn:maxx,1)==13)))...
                /length(find(comparement(:,2)==i))*100;
        case 13
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==14))+length(find(comparement(minn:maxx,1)==11))+length(find(comparement(minn:maxx,1)==12)))...
                /length(find(comparement(:,2)==i))*100;
        case 14
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==10))+length(find(comparement(minn:maxx,1)==11))+length(find(comparement(minn:maxx,1)==12))...
                +length(find(comparement(minn:maxx,1)==13))+length(find(comparement(minn:maxx,1)==15)))...
                /length(find(comparement(:,2)==i))*100;
        case 15
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==14))+length(find(comparement(minn:maxx,1)==10))+length(find(comparement(minn:maxx,1)==11))...
                +length(find(comparement(minn:maxx,1)==9))+length(find(comparement(minn:maxx,1)==16)))...
                /length(find(comparement(:,2)==i))*100;
        case 16
            percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
                +length(find(comparement(minn:maxx,1)==15))+length(find(comparement(minn:maxx,1)==9))+length(find(comparement(minn:maxx,1)==10)))...
                /length(find(comparement(:,2)==i))*100;
    end
end


%% 2nd neighbour percentage
for i=1:length(actTime2)
    minn=find(comparement(:,2)==i,1);
    maxx=find(comparement(:,2)==i,1,'last');
    switch i
        case 1
            percentage(i,3)=(length(find(comparement(minn:maxx,1)==1))...
                +length(find(comparement(minn:maxx,1)==2))+length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==8))...
                +length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==9))...
                +length(find(comparement(minn:maxx,1)==10))+length(find(comparement(minn:maxx,1)==11)))...
                /length(find(comparement(:,2)==i))*100;
        case 4
            percentage(i,3)=(length(find(comparement(minn:maxx,1)==2))...
                +length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==4))+length(find(comparement(minn:maxx,1)==6))...
                +length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==5))+length(find(comparement(minn:maxx,1)==10))...
                +length(find(comparement(minn:maxx,1)==11))+length(find(comparement(minn:maxx,1)==12)))...
                /length(find(comparement(:,2)==i))*100;
        case 13
            percentage(i,3)=(length(find(comparement(minn:maxx,1)==5))...
                +length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==10))...
                +length(find(comparement(minn:maxx,1)==11))+length(find(comparement(minn:maxx,1)==12))+length(find(comparement(minn:maxx,1)==13))...
                +length(find(comparement(minn:maxx,1)==14))+length(find(comparement(minn:maxx,1)==15)))...
                /length(find(comparement(:,2)==i))*100;
        case 16
            percentage(i,3)=(length(find(comparement(minn:maxx,1)==6))...
                +length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==8))+length(find(comparement(minn:maxx,1)==10))...
                +length(find(comparement(minn:maxx,1)==11))+length(find(comparement(minn:maxx,1)==9))+length(find(comparement(minn:maxx,1)==14))...
                +length(find(comparement(minn:maxx,1)==15))+length(find(comparement(minn:maxx,1)==16)))...
                /length(find(comparement(:,2)==i))*100;
        case {2,3}
            percentage(i,3)=(length(find(comparement(minn:maxx,1)==1))...
                +length(find(comparement(minn:maxx,1)==2))+length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==4))...
                +length(find(comparement(minn:maxx,1)==5))+length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==7))...
                +length(find(comparement(minn:maxx,1)==8))+length(find(comparement(minn:maxx,1)==9))+length(find(comparement(minn:maxx,1)==10))...
                +length(find(comparement(minn:maxx,1)==11))+length(find(comparement(minn:maxx,1)==12)))/length(find(comparement(:,2)==i))*100;
        case {5,12}
            percentage(i,3)=(length(find(comparement(minn:maxx,1)==2))...
                +length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==4))+length(find(comparement(minn:maxx,1)==5))...
                +length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==12))...
                +length(find(comparement(minn:maxx,1)==10))+length(find(comparement(minn:maxx,1)==11))+length(find(comparement(minn:maxx,1)==13))...
                +length(find(comparement(minn:maxx,1)==14))+length(find(comparement(minn:maxx,1)==15)))/length(find(comparement(:,2)==i))*100;
        case {8,9}
            percentage(i,3)=(length(find(comparement(minn:maxx,1)==1))...
                +length(find(comparement(minn:maxx,1)==2))+length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==6))...
                +length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==8))+length(find(comparement(minn:maxx,1)==10))...
                +length(find(comparement(minn:maxx,1)==11))+length(find(comparement(minn:maxx,1)==9))+length(find(comparement(minn:maxx,1)==14))...
                +length(find(comparement(minn:maxx,1)==15))+length(find(comparement(minn:maxx,1)==16)))/length(find(comparement(:,2)==i))*100;
        case {14,15}
            percentage(i,3)=(length(find(comparement(minn:maxx,1)==5))...
                +length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==8))...
                +length(find(comparement(minn:maxx,1)==9))+length(find(comparement(minn:maxx,1)==10))+length(find(comparement(minn:maxx,1)==11))...
                +length(find(comparement(minn:maxx,1)==12))+length(find(comparement(minn:maxx,1)==13))+length(find(comparement(minn:maxx,1)==14))...
                +length(find(comparement(minn:maxx,1)==15))+length(find(comparement(minn:maxx,1)==16)))/length(find(comparement(:,2)==i))*100;
        case {6,7,10,11}
            percentage(i,3)=(length(find(comparement(minn:maxx,1)==1))...
                +length(find(comparement(minn:maxx,1)==2))+length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==4))...
                +length(find(comparement(minn:maxx,1)==5))+length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==7))...
                +length(find(comparement(minn:maxx,1)==8))+length(find(comparement(minn:maxx,1)==9))+length(find(comparement(minn:maxx,1)==10))...
                +length(find(comparement(minn:maxx,1)==11))+length(find(comparement(minn:maxx,1)==12))+length(find(comparement(minn:maxx,1)==13))...
                +length(find(comparement(minn:maxx,1)==14))++length(find(comparement(minn:maxx,1)==15))+length(find(comparement(minn:maxx,1)==16)))...
                /length(find(comparement(:,2)==i))*100;
            
    end
end

percen=mean(percentage(:,1));

%resulting error CDF
for i=1:length(comparement)
[Y1,X1]=find(gridFormat==comparement(i,1));
if isempty(find(gridFormat==comparement(i,1), 1))
    Y1=2;
    X1=2;
end
[Y2,X2]=find(gridFormat==comparement(i,2));
CDFDiff(i)=sqrt(((Y1-Y2)*1.5).^2+((X1-X2)*1.5).^2);
end
hold on
ecdf(CDFDiff)
