%% 1-1 grid percentage
for i=1:length(actTime)
minn=find(comparement(:,2)==i,1);
maxx=find(comparement(:,2)==i,1,'last');
percentage(i,1)=length(find(comparement(minn:maxx,1)==i))/length(find(comparement(:,2)==i))*100;
end

%% 1st neighbor percentage
for i=1:length(actTime)
minn=find(comparement(:,2)==i,1);
maxx=find(comparement(:,2)==i,1,'last');
    switch i   
    case 1
    percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
    +length(find(comparement(minn:maxx,1)==2))+length(find(comparement(minn:maxx,1)==5))+length(find(comparement(minn:maxx,1)==6)))...
    /length(find(comparement(:,2)==i))*100;
    case 2
    percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
    +length(find(comparement(minn:maxx,1)==1))+length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==5))...
    +length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==7)))...
    /length(find(comparement(:,2)==i))*100; 
        case 3
    percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
    +length(find(comparement(minn:maxx,1)==2))+length(find(comparement(minn:maxx,1)==4))+length(find(comparement(minn:maxx,1)==6))...
    +length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==8)))...
    /length(find(comparement(:,2)==i))*100;          
        case 4
    percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
    +length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==8)))...
    /length(find(comparement(:,2)==i))*100;
        case 5
    percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
    +length(find(comparement(minn:maxx,1)==1))+length(find(comparement(minn:maxx,1)==2))+length(find(comparement(minn:maxx,1)==6))...
    +length(find(comparement(minn:maxx,1)==9))+length(find(comparement(minn:maxx,1)==10)))...
    /length(find(comparement(:,2)==i))*100;  
        case 6
    percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
    +length(find(comparement(minn:maxx,1)==1))+length(find(comparement(minn:maxx,1)==2))+length(find(comparement(minn:maxx,1)==3))...
    +length(find(comparement(minn:maxx,1)==5))+length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==9))...
    +length(find(comparement(minn:maxx,1)==10))++length(find(comparement(minn:maxx,1)==11)))...
    /length(find(comparement(:,2)==i))*100; 
        case 7
    percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
    +length(find(comparement(minn:maxx,1)==2))+length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==4))...
    +length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==8))+length(find(comparement(minn:maxx,1)==10))...
    +length(find(comparement(minn:maxx,1)==11))++length(find(comparement(minn:maxx,1)==12)))...
    /length(find(comparement(:,2)==i))*100; 
        case 8
    percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
    +length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==4))+length(find(comparement(minn:maxx,1)==7))...
    +length(find(comparement(minn:maxx,1)==11))+length(find(comparement(minn:maxx,1)==12)))...
    /length(find(comparement(:,2)==i))*100; 
        case 9
                percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
    +length(find(comparement(minn:maxx,1)==5))+length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==10)))...
    /length(find(comparement(:,2)==i))*100;
        case 10
                percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
    +length(find(comparement(minn:maxx,1)==9))+length(find(comparement(minn:maxx,1)==5))+length(find(comparement(minn:maxx,1)==6))...
    +length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==11)))...
    /length(find(comparement(:,2)==i))*100; 
        case 11
                percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
    +length(find(comparement(minn:maxx,1)==10))+length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==7))...
    +length(find(comparement(minn:maxx,1)==8))+length(find(comparement(minn:maxx,1)==12)))...
    /length(find(comparement(:,2)==i))*100; 
        case 12
                percentage(i,2)=(length(find(comparement(minn:maxx,1)==i))...
    +length(find(comparement(minn:maxx,1)==11))+length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==8)))...
    /length(find(comparement(:,2)==i))*100;
    end
end


%% 2nd neighbour percentage
for i=1:length(actTime)
minn=find(comparement(:,2)==i,1);
maxx=find(comparement(:,2)==i,1,'last');
    switch i   
    case {1,5,9}
    percentage(i,3)=(length(find(comparement(minn:maxx,1)==1))...
    +length(find(comparement(minn:maxx,1)==2))+length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==5))...
    +length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==9))...
    +length(find(comparement(minn:maxx,1)==10))+length(find(comparement(minn:maxx,1)==11)))...
    /length(find(comparement(:,2)==i))*100;
    case {2,3,6,7,10,11}
    percentage(i,3)=(length(find(comparement(minn:maxx,1)==1))...
    +length(find(comparement(minn:maxx,1)==2))+length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==4))...
    +length(find(comparement(minn:maxx,1)==5))+length(find(comparement(minn:maxx,1)==6))+length(find(comparement(minn:maxx,1)==7))...
    +length(find(comparement(minn:maxx,1)==8))+length(find(comparement(minn:maxx,1)==9))+length(find(comparement(minn:maxx,1)==10))...
    +length(find(comparement(minn:maxx,1)==11))+length(find(comparement(minn:maxx,1)==12)))...
    /length(find(comparement(:,2)==i))*100; 
    case {4,8,12}
    percentage(i,3)=(length(find(comparement(minn:maxx,1)==2))...
    +length(find(comparement(minn:maxx,1)==3))+length(find(comparement(minn:maxx,1)==4))+length(find(comparement(minn:maxx,1)==6))...
    +length(find(comparement(minn:maxx,1)==7))+length(find(comparement(minn:maxx,1)==8))+length(find(comparement(minn:maxx,1)==10))...
    +length(find(comparement(minn:maxx,1)==11))+length(find(comparement(minn:maxx,1)==12)))...
    /length(find(comparement(:,2)==i))*100;          
    end
end

percen=mean(percentage(:,1));